"""write cl415_description/urdf/cl415_generated.xacro from the pipeline outputs

inputs:  cad/geometry.json (joints, collision primitives, meshes), mass/mass_props.json (solidworks
         link inertials, full and empty), aero/aero_params.json (lift-drag and motor numbers)
output:  cl415_description/urdf/cl415_generated.xacro (properties and macros only, no links)

run from the project root:  .venv/Scripts/python tools/export_description.py
"""
import json
import math
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GEO = json.load(open(os.path.join(ROOT, 'cad', 'geometry.json')))
MASS = json.load(open(os.path.join(ROOT, 'mass', 'mass_props.json')))
AERO = json.load(open(os.path.join(ROOT, 'aero', 'aero_params.json')))
OUT = os.path.join(ROOT, 'cl415_description', 'urdf', 'cl415_generated.xacro')


def f(x, n=6):
    s = f'{x:.{n}g}'
    return '0' if s in ('-0', '0') else s


def v3(v, n=6):
    return ' '.join(f(x, n) for x in v)


def inertial(d, indent='    '):
    I = d['inertia']
    return (f'{indent}<inertial>\n'
            f'{indent}  <origin xyz="{v3(d["com"])}" rpy="0 0 0"/>\n'
            f'{indent}  <mass value="{f(d["mass"])}"/>\n'
            f'{indent}  <inertia ixx="{f(I["ixx"])}" ixy="{f(I["ixy"])}" ixz="{f(I["ixz"])}" '
            f'iyy="{f(I["iyy"])}" iyz="{f(I["iyz"])}" izz="{f(I["izz"])}"/>\n'
            f'{indent}</inertial>\n')


def collision(link, i, c, indent='    '):
    if c['type'] == 'box':
        g = f'<box size="{v3(c["size"])}"/>'
    else:
        g = f'<cylinder radius="{f(c["radius"])}" length="{f(c["length"])}"/>'
    return (f'{indent}<collision name="{link}_c{i}">\n'
            f'{indent}  <origin xyz="{v3(c["xyz"])}" rpy="{v3(c["rpy"])}"/>\n'
            f'{indent}  <geometry>{g}</geometry>\n'
            f'{indent}</collision>\n')


L = ['<?xml version="1.0"?>',
     '<!-- generated by tools/export_description.py, do not edit. numbers come from cad/geometry.json,',
     '     mass/mass_props.json (SolidWorks mass properties) and aero/aero_params.json -->',
     '<robot xmlns:xacro="http://www.ros.org/wiki/xacro">', '']

# joints
L.append('  <!-- joint frames (parent = base_link frame for every fixed part) -->')
for name, J in GEO['links'].items():
    if J['type'] == 'fixed':
        continue
    L.append(f'  <xacro:property name="{name}_xyz" value="{v3(J["xyz"])}"/>')
    L.append(f'  <xacro:property name="{name}_rpy" value="{v3(J["rpy"])}"/>')
    L.append(f'  <xacro:property name="{name}_axis" value="{v3(J["axis"])}"/>')
    L.append(f'  <xacro:property name="{name}_parent" value="{J["parent"]}"/>')
    if J['type'] == 'revolute':
        L.append(f'  <xacro:property name="{name}_limit" value="{f(math.radians(J["limit_deg"]))}"/>'
                 f'  <!-- {J["limit_deg"]:.0f} deg, positive = {J["positive"]} -->')
L.append('')

# inertials
L.append('  <!-- link inertials from SolidWorks (about the link CoM, link axes) -->')
for name in MASS['full']['links']:
    if name == 'water_tank':
        L.append('  <xacro:macro name="inertial_water_tank" params="tank">')
        L.append('    <xacro:if value="${tank == \'full\'}">')
        L.append(inertial(MASS['full']['links'][name], '      ').rstrip('\n'))
        L.append('    </xacro:if>')
        L.append('    <xacro:if value="${tank == \'empty\'}">')
        L.append(inertial(MASS['empty']['links'][name], '      ').rstrip('\n'))
        L.append('    </xacro:if>')
        L.append('  </xacro:macro>')
    else:
        L.append(f'  <xacro:macro name="inertial_{name}">')
        L.append(inertial(MASS['full']['links'][name]).rstrip('\n'))
        L.append('  </xacro:macro>')
L.append('')

# servo gains: torque-mode pid per surface, from the inertia about the hinge axis (solidworks numbers).
# natural frequency 80 rad/s, critically damped, integral zero at 3.2 rad/s (slow, just removes the sag), 0.5 N m stall torque
WN, ZETA, TAU_MAX = 80.0, 1.0, 0.5
L.append(f'  <!-- servo pid gains: p = I wn^2, d = 2 zeta wn I, i = p wn / 25, wn = {WN:.0f} rad/s, zeta = {ZETA},')
L.append(f'       I = inertia about the hinge axis; torque capped at {TAU_MAX} N m like a 5 kg cm servo -->')
for name in ('left_aileron', 'right_aileron', 'elevator', 'rudder'):
    d = MASS['full']['links'][name]
    I = d['inertia']
    Ic = [[I['ixx'], I['ixy'], I['ixz']], [I['ixy'], I['iyy'], I['iyz']], [I['ixz'], I['iyz'], I['izz']]]
    r = d['com']
    a = GEO['links'][name]['axis']
    rr = sum(x * x for x in r)
    ra = sum(x * y for x, y in zip(r, a))
    Ih = sum(a[i] * Ic[i][j] * a[j] for i in range(3) for j in range(3)) + d['mass'] * (rr - ra * ra)
    p = Ih * WN ** 2
    L.append(f'  <xacro:property name="servo_{name}_p" value="{f(p, 4)}"/>  <!-- hinge inertia {f(Ih, 3)} kg m^2 -->')
    L.append(f'  <xacro:property name="servo_{name}_d" value="{f(2 * ZETA * WN * Ih, 4)}"/>')
    L.append(f'  <xacro:property name="servo_{name}_i" value="{f(p * WN / 25, 4)}"/>')
L.append(f'  <xacro:property name="servo_torque_max" value="{TAU_MAX}"/>')
L.append('')

# collisions
L.append('  <!-- collision primitives (boxes / cylinders, sized from the CAD; the hull boxes keep the hull volume')
L.append('       so graded buoyancy floats it at the right draft) -->')
for name, cs in GEO['collision'].items():
    L.append(f'  <xacro:macro name="collision_{name}">')
    for i, c in enumerate(cs):
        L.append(collision(name, i, c).rstrip('\n'))
    L.append('  </xacro:macro>')
L.append('')

# aero: one LiftDrag per element, all on base_link (the fixed links are lumped into it in SDF)
L.append('  <!-- LiftDrag elements, see aero/report.md for where each number comes from -->')
L.append('  <xacro:macro name="lift_drag_plugins">')
for e in AERO['elements']:
    L += [f'    <!-- {e["name"]} -->',
          '    <gazebo>',
          '      <plugin filename="gz-sim-lift-drag-system" name="gz::sim::systems::LiftDrag">',
          '        <link_name>base_link</link_name>',
          f'        <air_density>{f(AERO["air_density"])}</air_density>',
          f'        <area>{f(e["area"])}</area>',
          f'        <cp>{v3(e["cp"])}</cp>',
          f'        <forward>{v3(e["forward"])}</forward>',
          f'        <upward>{v3(e["upward"])}</upward>',
          f'        <a0>{f(e["a0"])}</a0>',
          f'        <cla>{f(e["cla"])}</cla>',
          f'        <cda>{f(e["cda"])}</cda>',
          f'        <cma>{f(e["cma"])}</cma>',
          f'        <alpha_stall>{f(e["alpha_stall"])}</alpha_stall>',
          f'        <cla_stall>{f(e["cla_stall"])}</cla_stall>',
          f'        <cda_stall>{f(e["cda_stall"])}</cda_stall>',
          f'        <cma_stall>{f(e["cma_stall"])}</cma_stall>',
          f'        <control_joint_name>{e["control_joint"]}</control_joint_name>',
          f'        <control_joint_rad_to_cl>{f(e["control_joint_rad_to_cl"])}</control_joint_rad_to_cl>',
          f'        <cm_delta>{f(e["cm_delta"])}</cm_delta>',
          '      </plugin>',
          '    </gazebo>']
L.append('  </xacro:macro>')
L.append('')

# propulsion: counter-rotating, left ccw about its link z (= clockwise seen from behind)
m = AERO['motor']
L.append('  <!-- propulsion, one MulticopterMotorModel per prop. command: gz.msgs.Actuators on')
L.append('       /cl415/command/motor_speed, velocity[0] = left, velocity[1] = right, in rad/s -->')
L.append('  <xacro:macro name="motor_plugins">')
for i, (side, turn) in enumerate((('left', 'ccw'), ('right', 'cw'))):
    L += ['    <gazebo>',
          '      <plugin filename="gz-sim-multicopter-motor-model-system" name="gz::sim::systems::MulticopterMotorModel">',
          '        <robotNamespace>cl415</robotNamespace>',
          f'        <jointName>{side}_propeller_joint</jointName>',
          f'        <linkName>{side}_propeller</linkName>',
          f'        <turningDirection>{turn}</turningDirection>',
          f'        <timeConstantUp>{f(m["timeConstantUp"])}</timeConstantUp>',
          f'        <timeConstantDown>{f(m["timeConstantDown"])}</timeConstantDown>',
          f'        <maxRotVelocity>{f(m["maxRotVelocity"])}</maxRotVelocity>',
          f'        <motorConstant>{f(m["motorConstant"])}</motorConstant>',
          f'        <momentConstant>{f(m["momentConstant"])}</momentConstant>',
          '        <commandSubTopic>command/motor_speed</commandSubTopic>',
          f'        <motorNumber>{i}</motorNumber>',
          f'        <rotorDragCoefficient>{f(m["rotorDragCoefficient"])}</rotorDragCoefficient>',
          f'        <rollingMomentCoefficient>{f(m["rollingMomentCoefficient"])}</rollingMomentCoefficient>',
          f'        <rotorVelocitySlowdownSim>{f(m["rotorVelocitySlowdownSim"])}</rotorVelocitySlowdownSim>',
          '        <motorType>velocity</motorType>',
          '      </plugin>',
          '    </gazebo>']
L.append('  </xacro:macro>')
L.append('')
L.append('</robot>')
open(OUT, 'w', encoding='utf-8').write('\n'.join(L) + '\n')
print('wrote', os.path.relpath(OUT, ROOT), len(L), 'lines')
