function px4_export(gains, outfile, P)
%PX4_EXPORT  Write designed gains to a QGroundControl-format parameter file.
%
%   px4_export(gains, 'sim/px4_params.params', P)
%
% gains: struct of MATLAB-side gains, in the units the design produced:
%   .roll_rate  .pitch_rate  .yaw_rate  each with fields P, I, FF
%                 [rad of surface per rad/s]  (numerically = deg per deg/s)
%   .roll_tc    .pitch_tc   attitude time constants [s]  (= 1/k_phi, 1/k_theta)
%   .airspd_trim  design airspeed [m/s]
%   .rate_max   struct with roll, pitch_pos, pitch_neg, yaw  [deg/s]
%
% Conversion (see docs/decisions.md D-03):
%   PX4 rate gains are normalised actuator per rad/s; the mixer maps +-1 to
%   +-delta_max, so  K_PX4 = K_MATLAB / delta_max[rad].
%   Signs: PX4 +pitch torque is nose-up while our +de is nose-down; this is
%   handled by servo reversal in the airframe actuator setup, NOT here.
%
% The parameter NAMES below are from the PX4 v1.15/1.16 reference. Confirm
% every one in the pinned SITL (`param show FW_RR* FW_PR* FW_YR* FW_R_TC FW_P_TC
% FW_AIRSPD_TRIM FW_*RMAX*`) before flying; names change between releases.
%
% File format (QGC): "<vehicle_id> <component_id> <name> <value> <type>", type 9 = float.

    de = P.act.elevator.delta_max; da = P.act.aileron.delta_max; dr = P.act.rudder.delta_max;
    rows = {
        'FW_RR_P',  gains.roll_rate.P  / da
        'FW_RR_I',  gains.roll_rate.I  / da
        'FW_RR_FF', gains.roll_rate.FF / da
        'FW_PR_P',  gains.pitch_rate.P  / de
        'FW_PR_I',  gains.pitch_rate.I  / de
        'FW_PR_FF', gains.pitch_rate.FF / de
        'FW_YR_P',  gains.yaw_rate.P  / dr
        'FW_YR_I',  gains.yaw_rate.I  / dr
        'FW_YR_FF', gains.yaw_rate.FF / dr
        'FW_R_TC',  gains.roll_tc
        'FW_P_TC',  gains.pitch_tc
        'FW_AIRSPD_TRIM', gains.airspd_trim
        'FW_R_RMAX',      gains.rate_max.roll
        'FW_P_RMAX_POS',  gains.rate_max.pitch_pos
        'FW_P_RMAX_NEG',  gains.rate_max.pitch_neg
        'FW_Y_RMAX',      gains.rate_max.yaw
    };
    fid = fopen(outfile, 'w');
    fprintf(fid, '# PX4 parameters generated by matlab/px4_export.m\n');
    fprintf(fid, '# params.yaml sha256 %s   %s\n', P.meta.sha256, datestr(now));
    fprintf(fid, '# delta_max used for normalisation: de %.1f da %.1f dr %.1f deg\n', ...
            rad2deg(de), rad2deg(da), rad2deg(dr));
    fprintf(fid, '# CONFIRM parameter names in the pinned SITL before use.\n');
    for k = 1:size(rows, 1)
        fprintf(fid, '1\t1\t%s\t%.6g\t9\n', rows{k, 1}, rows{k, 2});
    end
    fclose(fid);
    fprintf('wrote %s (%d parameters)\n', outfile, size(rows, 1));
end
