"""step 4a: gazebo LiftDrag parameters and propulsion numbers, with the working shown

reads cad/geometry.json (areas, hinge lines, chord ratios) and mass/mass_props.json (cg, weight).
writes aero/aero_params.json (consumed by tools/export_description.py) and aero/report.md.

model: gz-sim LiftDrag (Harmonic). per element it computes, at the cp,
    alpha = a0 + (angle between the local flow and the forward vector, in the forward/upward plane)
    cl = cla * alpha            (cla_stall slope past alpha_stall), plus control_joint_rad_to_cl * delta
    cd = |cda * alpha|          (cda_stall past alpha_stall)
    cm = cma * alpha + cm_delta * delta, applied as cm * q * S (no chord factor in the plugin)
so a0 carries incidence and zero-lift angle, and cla/cda are the finite-wing values.

run from the project root:  .venv/Scripts/python aero/aero_params.py
"""
import json
import math
import os

import numpy as np

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GEO = json.load(open(os.path.join(ROOT, 'cad', 'geometry.json')))
MASS = json.load(open(os.path.join(ROOT, 'mass', 'mass_props.json')))
A = GEO['aero']
OUT = os.path.join(ROOT, 'aero')

RHO = 1.225          # kg/m^3, sea level ISA
NU = 1.46e-5         # m^2/s
G = 9.81
KAPPA = 0.95         # 2d lift slope / 2 pi (Raymer's airfoil efficiency for a real section)
CLMAX_2D_4417 = 1.35  # NACA 4417 near Re 4e5 (A&vD 4415/4418 give ~1.6 at Re 3e6, less at model Re)
CLMAX_2D_0016 = 1.20
DA_CLMAX = math.radians(1.5)   # DATCOM alpha increment to CLmax for an unswept high-AR wing
ETA_T = 0.90         # tail dynamic pressure ratio
ETA_V = 0.90
V_CRUISE = 20.0      # m/s, design point (tank full)
deg = math.degrees

L = []               # report lines


def say(s=''):
    L.append(s)


# thin airfoil theory on the actual naca 4417 camber line
def camber_slope(x, m=0.04, p=0.4):
    return np.where(x < p, 2 * m / p ** 2 * (p - x), 2 * m / (1 - p) ** 2 * (p - x))


th = np.linspace(0, math.pi, 20001)
xx = 0.5 * (1 - np.cos(th))
dz = camber_slope(xx)
alpha_L0 = -1 / math.pi * np.trapezoid(dz * (np.cos(th) - 1), th)
A1 = 2 / math.pi * np.trapezoid(dz * np.cos(th), th)
A2 = 2 / math.pi * np.trapezoid(dz * np.cos(2 * th), th)
cm_ac = math.pi / 4 * (A2 - A1)


def helmbold(AR, kappa=KAPPA, sweep_half=0.0, beta=1.0):
    """DATCOM / Raymer eq. 12.6 lift slope per rad"""
    return 2 * math.pi * AR / (2 + math.sqrt(4 + (AR * beta / kappa) ** 2 * (1 + math.tan(sweep_half) ** 2 / beta ** 2)))


def flap_tau(E):
    """thin-airfoil flap effectiveness d(alpha0)/d(delta) and d(cm_c/4)/d(delta), E = cf/c"""
    th_h = math.acos(2 * E - 1)
    tau = 1 - th_h / math.pi + math.sin(th_h) / math.pi
    dcm = -0.5 * math.sin(th_h) * (1 - math.cos(th_h))
    return tau, dcm


W = MASS['full']['mass'] * G
S = A['wing']['area_total']
b = A['wing']['span']
c = A['wing']['chord']
AR = A['wing']['aspect_ratio']
i_w = math.radians(A['wing']['incidence_deg'])
Re = V_CRUISE * c / NU
M = V_CRUISE / 340.3
beta = math.sqrt(1 - M * M)

say('# Step 4: aerodynamic parameters for the Gazebo LiftDrag plugin')
say()
say('Generated by `aero/aero_params.py`. Every number below is computed in that script from the CAD areas '
    '(`cad/geometry.json`) and the SolidWorks mass properties (`mass/mass_props.json`). Angles in the plugin '
    'are in radians; degrees are given alongside.')
say()
say('## Flight condition')
say()
say(f'- weight W = {MASS["full"]["mass"]:.2f} kg x {G} = {W:.1f} N (tank full)')
say(f'- wing: S = {S:.4f} m^2 (CAD planform, both halves), b = {b} m, c = {c} m, AR = b^2/S = {AR:.3f}')
say(f'- design cruise V = {V_CRUISE} m/s: q = {0.5 * RHO * V_CRUISE ** 2:.1f} Pa, Re = Vc/nu = {Re:.2e}, '
    f'M = {M:.3f} (beta = {beta:.4f}, so compressibility is ignored)')
CL_cruise = W / (0.5 * RHO * V_CRUISE ** 2 * S)
say(f'- cruise lift coefficient CL = W/(qS) = {CL_cruise:.3f}')
say()

# wing
a2d = KAPPA * 2 * math.pi
a_w = helmbold(AR, KAPPA, 0.0, beta)
CLmax = 0.9 * CLMAX_2D_4417
alpha_stall_zl = CLmax / a_w + DA_CLMAX
a0_w = i_w - alpha_L0
say('## Wing (NACA 4417), one LiftDrag element per half')
say()
say('Zero-lift angle and pitching moment from thin airfoil theory on the 4417 camber line '
    '(m = 0.04, p = 0.4), integrated numerically with x = (1 - cos theta)/2:')
say()
say(f'- alpha_L0 = -(1/pi) int (dz/dx)(cos theta - 1) dtheta = **{deg(alpha_L0):.2f} deg** ({alpha_L0:.4f} rad). '
    'Abbott & von Doenhoff list about -4.0 deg for the 4415 and 4418, so this is consistent.')
say(f'- A1 = {A1:.4f}, A2 = {A2:.4f}, cm_c/4 = (pi/4)(A2 - A1) = {cm_ac:.3f}')
say()
say(f'2-D lift slope: a0 = kappa 2 pi = {KAPPA} x 2 pi = {a2d:.3f} /rad ({a2d * math.pi / 180:.4f} /deg).')
say()
say('Finite-wing slope, DATCOM/Helmbold form (Raymer eq. 12.6), unswept:')
say()
say(f'    a = 2 pi AR / (2 + sqrt(4 + (AR beta/kappa)^2)) = 2 pi {AR:.3f} / (2 + sqrt(4 + ({AR:.3f} x {beta:.4f} / {KAPPA})^2))'
    f' = **{a_w:.3f} /rad**')
say()
say(f'Stall: CLmax_2D = {CLMAX_2D_4417} (4417 at Re ~4e5, A&vD values scaled down for the low Re), '
    f'CLmax_3D = 0.9 x CLmax_2D = {CLmax:.3f}. Angle from the zero-lift line: CLmax/a + 1.5 deg = '
    f'{deg(CLmax / a_w):.2f} + 1.5 = **{deg(alpha_stall_zl):.2f} deg** ({alpha_stall_zl:.4f} rad), i.e. '
    f'{deg(alpha_stall_zl + alpha_L0):.1f} deg to the chord, {deg(alpha_stall_zl + alpha_L0 - i_w):.1f} deg body AoA.')
say()
say(f'Plugin offset: forward = body +X, upward = body +Z, so a0 = i_w - alpha_L0 = {deg(i_w):.2f} + '
    f'{-deg(alpha_L0):.2f} = **{deg(a0_w):.2f} deg** ({a0_w:.4f} rad). Zero lift then happens at a body AoA of '
    f'{-deg(a0_w):.2f} deg.')
say()
# drag: component build-up for CD0, oswald e from raymer, then the plugin's linear cd
e_osw = 1.78 * (1 - 0.045 * AR ** 0.68) - 0.64


def cf_turb(Re_l):
    return 0.455 / (math.log10(Re_l) ** 2.58)


Sw_hull = 0.5 * GEO['parts']['fuselage']['area']            # outer half of the skin's two faces
Sw_nac = 2 * 0.5 * GEO['parts']['left_nacelle']['area']
Sw_flt = 2 * 0.5 * GEO['parts']['left_float']['area']
L_hull = GEO['misc']['nose_x'] - GEO['misc']['stern_x']
d_hull = 2 * 0.1155
f_hull = L_hull / d_hull
comp = []
comp.append(('hull (step + spray rails, Q = 1.25)', cf_turb(V_CRUISE * L_hull / NU), 1 + 60 / f_hull ** 3 + f_hull / 400, 1.25, Sw_hull))
comp.append(('nacelles (Q = 1.3)', cf_turb(V_CRUISE * 0.43 / NU), 1 + 0.35 / (0.43 / 0.085), 1.3, Sw_nac))
comp.append(('floats + pylons (Q = 1.2)', cf_turb(V_CRUISE * 0.26 / NU), 1.2, 1.2, Sw_flt))
tc_h, tc_v = 0.16, 0.12
comp.append(('h-stab + elevator', cf_turb(V_CRUISE * A['htail']['chord'] / NU), 1 + 2 * tc_h + 100 * tc_h ** 4, 1.05,
             2.04 * A['htail']['area']))
comp.append(('fin + rudder + finlets', cf_turb(V_CRUISE * A['vtail']['mac'] / NU), 1 + 2 * tc_v + 100 * tc_v ** 4, 1.05,
             2.04 * (A['vtail']['area'] + 2 * A['finlets']['area_each'])))
cd0_wing = 0.012
CD0_rest = sum(cf * ff * q * sw / S for _, cf, ff, q, sw in comp) * 1.10
CD0 = cd0_wing + CD0_rest
CDi = CL_cruise ** 2 / (math.pi * e_osw * AR)
CD_cruise = CD0 + CDi
alpha_cr = CL_cruise / a_w
cda_w = CD_cruise / alpha_cr
say('Drag. The plugin only knows cd = |cda alpha| with alpha measured from zero lift, so it has no '
    'separate CD0. The whole-aircraft drag at the cruise point is put on the two wing halves:')
say()
say('| component | Cf (turbulent) | form factor | Q | S_wet [m^2] | CD0 contribution |')
say('|---|---:|---:|---:|---:|---:|')
for nm, cf, ff, q, sw in comp:
    say(f'| {nm} | {cf:.5f} | {ff:.3f} | {q:.2f} | {sw:.3f} | {cf * ff * q * sw / S:.5f} |')
say(f'| wing profile drag (4417 at Re 4e5) | | | | | {cd0_wing:.5f} |')
say(f'| leakage and protuberances | | | | | +10 % of the non-wing items |')
say(f'| **CD0** | | | | | **{CD0:.4f}** |')
say()
say(f'- Oswald factor (Raymer eq. 12.48) e = 1.78(1 - 0.045 AR^0.68) - 0.64 = {e_osw:.3f}')
say(f'- at cruise: CDi = CL^2/(pi e AR) = {CDi:.4f}, CD = {CD_cruise:.4f}, L/D = {CL_cruise / CD_cruise:.1f}, '
    f'drag = {CD_cruise * 0.5 * RHO * V_CRUISE ** 2 * S:.1f} N')
say(f'- plugin alpha at cruise = CL/a = {alpha_cr:.4f} rad, so **cda = CD/alpha = {cda_w:.3f} /rad**. That '
    'reproduces the polar at cruise, overestimates drag a little near stall and underestimates it near zero lift.')
say()
cla_stall_w = -0.4 * CLmax / math.radians(15)
cd_45 = 1.0
cda_stall_w = (cd_45 - cda_w * alpha_stall_zl) / (math.radians(45) - alpha_stall_zl)
say(f'Post-stall (rough): lift falls to 60 % of CLmax 15 deg past stall, cla_stall = -0.4 CLmax / 15 deg = '
    f'{cla_stall_w:.3f} /rad; drag reaches a flat-plate-like CD ~ 1 at 45 deg, cda_stall = {cda_stall_w:.3f} /rad.')
say()
y_half = b / 4
x_qc, _, z_qc = A['wing']['ac_left']
say(f'Centre of pressure: quarter chord of each half at its area centroid, cp = ({x_qc:.4f}, +/-{y_half:.4f}, '
    f'{z_qc:.4f}) m in base_link. A single point per half at b/4 gives roll damping Clp = -2 a (y/b)^2 = '
    f'{-2 * a_w * (y_half / b) ** 2:.3f}, close to DATCOM for a rectangular AR 9 wing (about -0.6), so the area '
    'centroid is a reasonable single point.')
say()
say(f'Pitching moment: the 4417 has cm_ac = {cm_ac:.3f}, a constant. LiftDrag can only do cm = cma alpha, which would '
    'add a fake pitch stiffness, so cma = 0 on the wing and the camber moment is left out. In practice the '
    'sim needs a bit less up-elevator to trim than the real aircraft would.')
say()

# ailerons
E_a = A['aileron']['cf_c']
tau_a, dcm_a = flap_tau(E_a)
y0a, y1a = A['aileron']['y']
frac_a = (y1a - y0a) * c / A['wing']['area_left']
y_ail = 0.5 * (y0a + y1a)
dCL_a = a_w * tau_a * frac_a
k_arm = y_ail / y_half
ail_cl = dCL_a * k_arm
Cl_da = 2 * dCL_a * A['wing']['area_left'] * y_ail / (S * b)
say('## Ailerons (coupled to the wing halves)')
say()
say(f'- chord ratio E = cf/c = {E_a:.3f}; thin airfoil: theta_h = acos(2E - 1) = {math.acos(2 * E_a - 1):.4f}, '
    f'tau = 1 - theta_h/pi + sin(theta_h)/pi = **{tau_a:.3f}**, dcm/ddelta = -1/2 sin(theta_h)(1 - cos(theta_h)) = {dcm_a:.3f}')
say(f'- flapped share of a half wing: c (y1 - y0) / S_half = {c} x {y1a - y0a:.3f} / {A["wing"]["area_left"]:.4f} = {frac_a:.3f}')
say(f'- half-wing lift per radian: dCL/ddelta = a tau (S_flapped/S_half) = {a_w:.3f} x {tau_a:.3f} x {frac_a:.3f} = {dCL_a:.3f}')
say(f'- the plugin puts that lift at the half-wing cp (y = {y_half:.4f}) but it really acts at the aileron centre '
    f'(y = {y_ail:.3f}), so the coefficient is scaled by {k_arm:.3f} to keep the roll moment right: '
    f'**control_joint_rad_to_cl = {ail_cl:.3f}**. Ailerons move in opposite directions, so the extra lift cancels '
    'and only the roll moment remains.')
say(f'- resulting roll control power Cl_delta_a = 2 dCL S_half y_ail / (S b) = {Cl_da:.4f} /rad per aileron degree of '
    f'differential (both deflected by delta)')
cm_delta_a = 0.9 * dcm_a * frac_a * c
say(f'- cm_delta = 0.9 dcm/ddelta (S_flapped/S_half) c = {cm_delta_a:.5f} (chord factor because the plugin applies cm q S)')
say()

# horizontal tail
S_h = A['htail']['area']
AR_h = A['htail']['span'] ** 2 / S_h
a_h = helmbold(AR_h, KAPPA, 0.0, beta)
deda = 2 * a_w / (math.pi * AR)
l_h = A['wing']['ac_left'][0] - A['htail']['ac'][0]
V_H = S_h * l_h / (S * c)
cla_h = a_h * ETA_T * (1 - deda)
a0_h = (0.0 - deda * a0_w) / (1 - deda)
CLmax_h = 0.9 * CLMAX_2D_0016
alpha_stall_h = (CLmax_h / a_h + DA_CLMAX) / (1 - deda)
E_e = A['htail']['cf_c']
tau_e, dcm_e = flap_tau(E_e)
# share of the full-span flapped strip the cad elevator really covers: its area aft of the hinge
# (cad area minus the round nose ahead of it) over E c b
r_e = 5 * 0.16 * (0.2969 * math.sqrt(1 - E_e) - 0.126 * (1 - E_e) - 0.3516 * (1 - E_e) ** 2
                  + 0.2843 * (1 - E_e) ** 3 - 0.1015 * (1 - E_e) ** 4) * A['htail']['chord']
el_half = A['htail']['span'] / 2 - A['htail']['elevator_inner_y']
cov_e = (A['htail']['elevator_area'] - r_e * 2 * el_half) / (E_e * A['htail']['chord'] * A['htail']['span'])
elev_cl = a_h * tau_e * cov_e * ETA_T
cm_delta_e = 0.9 * dcm_e * cov_e * A['htail']['chord'] * ETA_T
cda_h = (0.008 + (a_h * 0.0873) ** 2 / (math.pi * 0.8 * AR_h)) / 0.0873
say('## Horizontal tail (NACA 0016) with elevator')
say()
say(f'- S_h = {S_h:.4f} m^2 (CAD, gross through the fin), span {A["htail"]["span"]:.3f} m, AR_h = {AR_h:.3f}, incidence 0 (OBJ)')
say(f'- a_h = 2 pi AR_h / (2 + sqrt(4 + (AR_h/kappa)^2)) = **{a_h:.3f} /rad**')
say(f'- downwash: deps/dalpha = 2 a_w / (pi AR) = {deda:.4f}; at zero body AoA the wing CL is a_w a0_w = '
    f'{a_w * a0_w:.3f}, so eps0 = {deda * a0_w:.4f} rad ({deg(deda * a0_w):.2f} deg)')
say(f'- the plugin sees free-stream flow at the tail, so downwash and the tail dynamic pressure ratio '
    f'(eta_t = {ETA_T}) are folded into the coefficients:')
say(f'    cla_eff = a_h eta_t (1 - deps/dalpha) = {a_h:.3f} x {ETA_T} x {1 - deda:.4f} = **{cla_h:.3f} /rad**')
say(f'    a0_eff = (i_t - deps/dalpha a0_w) / (1 - deps/dalpha) = **{a0_h:.4f} rad** ({deg(a0_h):.2f} deg)')
say(f'- stall: CLmax_t = 0.9 x {CLMAX_2D_0016} = {CLmax_h:.2f}, true tail angle {deg(CLmax_h / a_h + DA_CLMAX):.1f} deg, '
    f'in plugin alpha (divide by 1 - deps/dalpha) **{alpha_stall_h:.4f} rad**')
say(f'- elevator: E = {E_e:.3f}, tau = {tau_e:.3f}; the CAD elevator covers {cov_e:.3f} of the full-span flapped strip (fin gap, rudder cut-outs); '
    f'**control_joint_rad_to_cl = a_h tau coverage eta_t = {elev_cl:.3f}**, cm_delta = {cm_delta_e:.5f}')
say(f'- drag: cda linearised at 5 deg with CD0 = 0.008 and e = 0.8, cda = {cda_h:.3f} /rad')
say(f'- tail volume V_H = S_h l_h / (S c) = {S_h:.4f} x {l_h:.4f} / ({S:.4f} x {c}) = {V_H:.3f} (the CL-415 has a big tail)')
say()

# vertical tail + finlets
S_v = A['vtail']['area']
S_fl = 2 * A['finlets']['area_each']
AR_vg = A['vtail']['height'] ** 2 / S_v
AR_ve = 1.5 * AR_vg
VT = A['vtail']
te_r = VT['hinge_root'][0] - VT['cf_c_root'] * VT['root_chord']
te_t = VT['hinge_tip'][0] - VT['cf_c_tip'] * VT['tip_chord']
xr_mid = te_r + 0.5 * VT['root_chord']
xt_mid = te_t + 0.5 * VT['tip_chord']
sweep_v = math.atan((xr_mid - xt_mid) / A['vtail']['height'])
a_v = helmbold(AR_ve, KAPPA, sweep_v, beta)
AR_fl = A['finlets']['height'] ** 2 / A['finlets']['area_each']
a_fl = helmbold(AR_fl, KAPPA, 0.0, beta)
S_vt = S_v + S_fl
cla_v = (a_v * S_v + a_fl * S_fl) / S_vt * ETA_V
fl_c = A['finlets']['centroid_left']
x_fl_ac = fl_c[0] - 0.25 * (A['finlets']['area_each'] / A['finlets']['height'])
cp_v = [(A['vtail']['ac'][0] * S_v + x_fl_ac * S_fl) / S_vt, 0.0, (A['vtail']['ac'][2] * S_v + fl_c[2] * S_fl) / S_vt]
E_r = 0.5 * (A['vtail']['cf_c_root'] + A['vtail']['cf_c_tip'])
tau_r, dcm_r = flap_tau(E_r)
rud_cl = -a_v * tau_r * ETA_V * S_v / S_vt
cm_delta_r = -0.9 * dcm_r * A['vtail']['mac'] * ETA_V * S_v / S_vt
alpha_stall_v = math.radians(23.0)
cda_v = (0.008 + (a_v * 0.1) ** 2 / (math.pi * 0.8 * AR_ve)) / 0.1
l_v = MASS['full']['cg'][0] - cp_v[0]
V_V = S_vt * l_v / (S * b)
say('## Vertical tail (NACA 0012) + finlets, one element, with rudder')
say()
say(f'- fin + rudder above the deck: S_v = {S_v:.4f} m^2, height {A["vtail"]["height"]:.4f} m, geometric AR = {AR_vg:.3f}; '
    f'the hull below and the stab at mid-height act as end plates, effective AR = 1.5 x {AR_vg:.3f} = {AR_ve:.3f}')
say(f'- half-chord sweep {deg(sweep_v):.1f} deg; a_v = helmbold(AR_eff, sweep) = {a_v:.3f} /rad')
say(f'- finlets (two, on the stab): {S_fl:.4f} m^2 total, AR {AR_fl:.2f} each, a_fl = {a_fl:.3f} /rad')
say(f'- one element for all vertical area: S = {S_vt:.4f} m^2, cla = (a_v S_v + a_fl S_fl)/S x eta_v = **{cla_v:.3f} /rad**, '
    f'a0 = 0 (symmetric), cp = area-weighted quarter-chord point ({cp_v[0]:.4f}, 0, {cp_v[2]:.4f})')
say(f'- forward = +X, upward = +Y, so the plugin angle is the sideslip; alpha_stall = 23 deg (low AR fins stall late)')
say(f'- rudder: E = {E_r:.3f} (mean of root and tip), tau = {tau_r:.3f}. Positive rudder = trailing edge left, which pushes '
    f'the tail right (-Y), so **control_joint_rad_to_cl = -a_v tau eta_v S_v/S = {rud_cl:.3f}**, cm_delta = {cm_delta_r:.5f}')
say(f'- drag: cda = {cda_v:.3f} /rad (linearised at 0.1 rad sideslip)')
say(f'- vertical tail volume V_V = S l_v / (S_w b) = {V_V:.3f}')
say()

# static margin
K_f = 0.011
W_f, L_f = d_hull, L_hull
Cma_fus = K_f * W_f ** 2 * L_f / (c * S) * 180 / math.pi
dh_fus = Cma_fus / a_w
h_n_plugin = 0.25 + ETA_T * V_H * (a_h / a_w) * (1 - deda)
h_n = h_n_plugin - dh_fus
say('## Static margin check')
say()
say(f'- neutral point from the surfaces only (what the plugin model contains): h_n = 0.25 + eta V_H (a_h/a_w)(1 - deps/dalpha) '
    f'= {h_n_plugin:.3f}')
say(f'- hull destabilising term (Gilruth/Raymer, K_f = {K_f}/deg at 39 % hull length): dCm/dalpha = {Cma_fus:.3f} /rad, '
    f'shifts h_n forward by {dh_fus:.3f}, so h_n ~ {h_n:.3f} for the real aircraft')
for case in ('full', 'empty'):
    h = MASS[case]['cg_pct_mac'] / 100
    say(f'- {case}: CG at {100 * h:.1f} % MAC, static margin {100 * (h_n - h):.0f} % MAC (plugin model {100 * (h_n_plugin - h):.0f} %)')
say('- a big margin, as expected with V_H near 0.9. Elevator authority is the thing to watch at low speed.')
say()

# propulsion
D = A['props']['diameter']
CT0, CP0 = 0.085, 0.045
RPM_MAX = 8500.0
n_max = RPM_MAX / 60
w_max = 2 * math.pi * n_max
T_max = CT0 * RHO * n_max ** 2 * D ** 4
kT = T_max / w_max ** 2
Q_T = (CP0 / (2 * math.pi)) * D / CT0
P_max = CP0 * RHO * n_max ** 3 * D ** 5
say('## Propulsion (MulticopterMotorModel, one per propeller)')
say()
say(f'- prop D = {D:.4f} m (OBJ scaled), 14x7 class. Static coefficients assumed CT = {CT0}, CP = {CP0}.')
say(f'- max {RPM_MAX:.0f} rpm = {w_max:.1f} rad/s: T_max = CT rho n^2 D^4 = {T_max:.1f} N per motor, '
    f'{2 * T_max / W:.2f} T/W with both (tank full); shaft power {P_max:.0f} W each')
say(f'- motorConstant = T_max / w_max^2 = **{kT:.4e} N/(rad/s)^2**, momentConstant = (CP/2pi) D / CT = **{Q_T:.4f} m**')
say(f'- cruise needs {CD_cruise * 0.5 * RHO * V_CRUISE ** 2 * S:.1f} N total. The plugin thrust is static (no '
    'advance-ratio drop), so in flight it gives more thrust per rpm than a real prop would.')
say('- props counter-rotate: left one clockwise seen from behind (positive about +X), right one counter-clockwise, '
    'both blades going up on the outboard side. The CAD blades are pitched to match.')
say()

elements = [
    {'name': 'left_wing', 'cp': [x_qc, y_half, z_qc], 'forward': [1, 0, 0], 'upward': [0, 0, 1],
     'area': A['wing']['area_left'], 'a0': a0_w, 'cla': a_w, 'cda': cda_w, 'cma': 0.0, 'alpha_stall': alpha_stall_zl,
     'cla_stall': cla_stall_w, 'cda_stall': cda_stall_w, 'cma_stall': 0.0, 'control_joint': 'left_aileron_joint',
     'control_joint_rad_to_cl': ail_cl, 'cm_delta': cm_delta_a},
    {'name': 'right_wing', 'cp': [x_qc, -y_half, z_qc], 'forward': [1, 0, 0], 'upward': [0, 0, 1],
     'area': A['wing']['area_right'], 'a0': a0_w, 'cla': a_w, 'cda': cda_w, 'cma': 0.0, 'alpha_stall': alpha_stall_zl,
     'cla_stall': cla_stall_w, 'cda_stall': cda_stall_w, 'cma_stall': 0.0, 'control_joint': 'right_aileron_joint',
     'control_joint_rad_to_cl': ail_cl, 'cm_delta': cm_delta_a},
    {'name': 'h_stab', 'cp': A['htail']['ac'], 'forward': [1, 0, 0], 'upward': [0, 0, 1], 'area': S_h, 'a0': a0_h,
     'cla': cla_h, 'cda': cda_h, 'cma': 0.0, 'alpha_stall': alpha_stall_h, 'cla_stall': -0.5 * cla_h,
     'cda_stall': 1.0, 'cma_stall': 0.0, 'control_joint': 'elevator_joint', 'control_joint_rad_to_cl': elev_cl,
     'cm_delta': cm_delta_e},
    {'name': 'v_stab', 'cp': cp_v, 'forward': [1, 0, 0], 'upward': [0, 1, 0], 'area': S_vt, 'a0': 0.0, 'cla': cla_v,
     'cda': cda_v, 'cma': 0.0, 'alpha_stall': alpha_stall_v, 'cla_stall': -0.5 * cla_v, 'cda_stall': 1.0,
     'cma_stall': 0.0, 'control_joint': 'rudder_joint', 'control_joint_rad_to_cl': rud_cl, 'cm_delta': cm_delta_r},
]
say('## Plugin parameters (all elements on base_link; fixed links are lumped into it in SDF)')
say()
say('| element | area [m^2] | cp [m] | a0 [rad] | cla | cda | alpha_stall [rad] | cla_stall | cda_stall | control joint | rad_to_cl | cm_delta |')
say('|---|---:|---|---:|---:|---:|---:|---:|---:|---|---:|---:|')
for e in elements:
    say(f'| {e["name"]} | {e["area"]:.4f} | ({e["cp"][0]:.4f}, {e["cp"][1]:.4f}, {e["cp"][2]:.4f}) | {e["a0"]:.4f} | '
        f'{e["cla"]:.3f} | {e["cda"]:.3f} | {e["alpha_stall"]:.4f} | {e["cla_stall"]:.3f} | {e["cda_stall"]:.3f} | '
        f'{e["control_joint"]} | {e["control_joint_rad_to_cl"]:.3f} | {e["cm_delta"]:.5f} |')
say()
say('Known limits of this model: no constant wing pitching moment, no downwash lag, no propeller slipstream, '
    'no hull lift or side force, linear control effectiveness up to the joint limits, and drag tuned to one '
    'point. Good enough for controller work and sanity flights; swap to AdvancedLiftDrag with a full derivative '
    'set once wind-tunnel or XFLR5 data exists.')

out = {'air_density': RHO, 'elements': elements,
       'motor': {'motorConstant': kT, 'momentConstant': Q_T, 'maxRotVelocity': w_max, 'timeConstantUp': 0.0125,
                 'timeConstantDown': 0.025, 'rotorDragCoefficient': 1.0e-4, 'rollingMomentCoefficient': 1.0e-6,
                 'rotorVelocitySlowdownSim': 10.0, 'T_max_N': T_max},
       'derived': {'alpha_L0': alpha_L0, 'cm_ac': cm_ac, 'a_w': a_w, 'a_h': a_h, 'a_v': a_v, 'deps_dalpha': deda,
                   'CL_cruise': CL_cruise, 'CD0': CD0, 'e': e_osw, 'V_H': V_H, 'V_V': V_V, 'h_n_plugin': h_n_plugin,
                   'h_n': h_n, 'Cl_delta_a': Cl_da, 'V_cruise': V_CRUISE,
                   'V_stall_full': math.sqrt(2 * W / (RHO * S * CLmax))}}
json.dump(out, open(os.path.join(OUT, 'aero_params.json'), 'w'), indent=1)
say()
say(f'Stall speed at 10.5 kg: V_s = sqrt(2W/(rho S CLmax)) = {out["derived"]["V_stall_full"]:.1f} m/s.')
open(os.path.join(OUT, 'report.md'), 'w', encoding='utf-8').write('\n'.join(L) + '\n')
print('\n'.join(L))
