 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: CL-415 UAV 2.51 m span (cl415_description)                  
     # Surfaces =  13
     # Strips   = 174
     # Vortices =1856

  Sref = 0.69804       Cref = 0.27800       Bref =  2.5100    
  Xref = 0.77860E-01   Yref =  0.0000       Zref =-0.65860E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =  -1.13172     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.03306     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =  -0.00000     Cmtot =  -0.00000
  CZtot =  -0.42965     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   0.43022
  CDtot =   0.02457
  CDvis =   0.00000     CDind = 0.0245671
  CLff  =   0.41415     CDff  = 0.0072723    | Trefftz
  CYff  =  -0.00000         e =    0.8318    | Plane  

   aileron         =   0.00000
   elevator        =   2.08938
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.608997    CLb =  -0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.470763
 x  force CD |    CDa =   0.159799    CDb =  -0.000000
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.055387
 y  mom.  Cm |    Cma =  -1.403255    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.070901

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =  10.128964    CLr =   0.000000
 y  force CY |    CYp =  -0.000517    CYq =   0.000000    CYr =   0.201382
 x  force CD |    CDp =  -0.000000    CDq =   0.248454    CDr =  -0.000000
 x' mom.  Cl'|    Clp =  -0.550351    Clq =  -0.000000    Clr =   0.157544
 y  mom.  Cm |    Cmp =   0.000000    Cmq = -20.484331    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.022720    Cnq =  -0.000000    Cnr =  -0.117330

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.014368   CLd03 =   0.000000
 y  force CY |   CYd01 =  -0.000240   CYd02 =  -0.000000   CYd03 =   0.004695
 x  force CD |   CDd01 =  -0.000000   CDd02 =   0.000065   CDd03 =   0.000000
 x' mom.  Cl'|   Cld01 =   0.004403   Cld02 =   0.000000   Cld03 =   0.000482
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.040302   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000207   Cnd02 =   0.000000   Cnd03 =  -0.001677
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000065 CDffd03 =   0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.050278    ed03 =  -0.000000



 Neutral point  Xnp =   0.147410

 Clb Cnr / Clr Cnb  =   0.581782    (  > 1 if spirally stable )
