 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: CL-415 UAV 2.51 m span (cl415_description)                  
     # Surfaces =  13
     # Strips   = 174
     # Vortices =1856

  Sref = 0.69804       Cref = 0.27800       Bref =  2.5100    
  Xref = 0.77860E-01   Yref =  0.0000       Zref =-0.65860E-01

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.00000     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.02817     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =  -0.00000     Cmtot =   0.05629
  CZtot =  -0.51049     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   0.51049
  CDtot =   0.02817
  CDvis =   0.00000     CDind = 0.0281733
  CLff  =   0.49561     CDff  = 0.0104828    | Trefftz
  CYff  =  -0.00000         e =    0.8264    | Plane  

   aileron         =   0.00000
   elevator        =   0.00000
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.592843    CLb =  -0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.469932
 x  force CD |    CDa =   0.185895    CDb =  -0.000000
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.053605
 y  mom.  Cm |    Cma =  -1.446929    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.071549

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =  10.142496    CLr =  -0.000000
 y  force CY |    CYp =   0.003622    CYq =   0.000000    CYr =   0.201279
 x  force CD |    CDp =  -0.000000    CDq =   0.327754    CDr =  -0.000000
 x' mom.  Cl'|    Clp =  -0.547608    Clq =  -0.000000    Clr =   0.178015
 y  mom.  Cm |    Cmp =   0.000000    Cmq = -20.728299    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.031416    Cnq =  -0.000000    Cnr =  -0.119497

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.014364   CLd03 =   0.000000
 y  force CY |   CYd01 =  -0.000238   CYd02 =  -0.000000   CYd03 =   0.004659
 x  force CD |   CDd01 =  -0.000000   CDd02 =   0.000043   CDd03 =   0.000000
 x' mom.  Cl'|   Cld01 =   0.004386   Cld02 =   0.000000   Cld03 =   0.000443
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.040513   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000259   Cnd02 =   0.000000   Cnd03 =  -0.001673
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000043 CDffd03 =   0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.044529    ed03 =  -0.000000



 Neutral point  Xnp =   0.149782

 Clb Cnr / Clr Cnb  =   0.502917    (  > 1 if spirally stable )
