 ---------------------------------------------------------------
 Vortex Lattice Output -- Total Forces

 Configuration: CL-415 UAV 2.51 m span (cl415_description)                  
     # Surfaces =  13
     # Strips   = 174
     # Vortices =1856

  Sref = 0.69804       Cref = 0.27800       Bref =  2.5100    
  Xref = 0.75450E-01   Yref =  0.0000       Zref =-0.10066    

 Standard axis orientation,  X fwd, Z down         

 Run case:  -unnamed-                              

  Alpha =   0.82510     pb/2V =  -0.00000     p'b/2V =  -0.00000
  Beta  =   0.00000     qc/2V =   0.00000
  Mach  =     0.000     rb/2V =  -0.00000     r'b/2V =  -0.00000

  CXtot =  -0.02279     Cltot =  -0.00000     Cl'tot =  -0.00000
  CYtot =  -0.00000     Cmtot =  -0.00000
  CZtot =  -0.60269     Cntot =   0.00000     Cn'tot =   0.00000

  CLtot =   0.60230
  CDtot =   0.03147
  CDvis =   0.00000     CDind = 0.0314675
  CLff  =   0.58839     CDff  = 0.0135290    | Trefftz
  CYff  =  -0.00000         e =    0.9025    | Plane  

   aileron         =   0.00000
   elevator        =   0.80987
   rudder          =   0.00000

 ---------------------------------------------------------------

 Stability-axis derivatives...

                             alpha                beta
                  ----------------    ----------------
 z' force CL |    CLa =   5.577623    CLb =  -0.000000
 y  force CY |    CYa =  -0.000000    CYb =  -0.470938
 x  force CD |    CDa =   0.225805    CDb =  -0.000000
 x' mom.  Cl'|    Cla =   0.000000    Clb =  -0.058853
 y  mom.  Cm |    Cma =  -1.589160    Cmb =   0.000000
 z' mom.  Cn'|    Cna =   0.000000    Cnb =   0.073205

                     roll rate  p'      pitch rate  q'        yaw rate  r'
                  ----------------    ----------------    ----------------
 z' force CL |    CLp =  -0.000000    CLq =   9.873476    CLr =   0.000000
 y  force CY |    CYp =  -0.006508    CYq =   0.000000    CYr =   0.203351
 x  force CD |    CDp =  -0.000000    CDq =   0.292633    CDr =   0.000000
 x' mom.  Cl'|    Clp =  -0.546902    Clq =  -0.000000    Clr =   0.197136
 y  mom.  Cm |    Cmp =  -0.000000    Cmq = -20.778000    Cmr =   0.000000
 z' mom.  Cn'|    Cnp =  -0.036190    Cnq =  -0.000000    Cnr =  -0.121987

                  aileron      d01     elevator     d02     rudder       d03 
                  ----------------    ----------------    ----------------
 z' force CL |   CLd01 =  -0.000000   CLd02 =   0.014355   CLd03 =   0.000000
 y  force CY |   CYd01 =  -0.000238   CYd02 =  -0.000000   CYd03 =   0.004662
 x  force CD |   CDd01 =  -0.000000   CDd02 =   0.000253   CDd03 =  -0.000000
 x' mom.  Cl'|   Cld01 =   0.004367   Cld02 =   0.000000   Cld03 =   0.000481
 y  mom.  Cm |   Cmd01 =   0.000000   Cmd02 =  -0.040609   Cmd03 =  -0.000000
 z' mom.  Cn'|   Cnd01 =  -0.000296   Cnd02 =   0.000000   Cnd03 =  -0.001686
 Trefftz drag| CDffd01 =  -0.000000 CDffd02 =   0.000252 CDffd03 =   0.000000
 span eff.   |    ed01 =   0.000000    ed02 =   0.027220    ed03 =  -0.000000



 Neutral point  Xnp =   0.154657

 Clb Cnr / Clr Cnb  =   0.497483    (  > 1 if spirally stable )
